@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.gjhi.tinkersinnovation.hooks;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;