@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.gjhi.tinkersinnovation.modifiers;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;